---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: concource-pipelines-repo
  - name: from
    path: repo-target
  - name: to
    path: repo
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - concource-pipelines-repo/tasks/merge-branch.sh
