# all secret values are invalid and shown for demonstration purposes only
---
apiVersion: v1
kind: Secret
metadata:
  name: rails-react-boilerplate.git-repo
  namespace: concourse-main
type: Opaque
stringData:
  name: ilyasotkov/rails-react-boilerplate
  uri: git@github.com:ilyasotkov/rails-react-boilerplate.git
  token: 0565d48536e447d8851e82ff855b9d3f1160548d
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQC0Tp3p5Mox35XV1npSEEvXyTsHPg8HMJsU75Cc4SgFad28lmml
    CJsE7Ri46/5yeSmICY67x9J4rMABBxarliuK4QOn4EUcRIcPBKZOpD2c8FFFzIWq
    QWLo2xCf1JhJDDrGhjosnI/b30tYJyU6tE3IbWLfH07Re7yYva93PcxISQIDAQAB
    AoGANJNwDJHAO8a8hDwkMuW5l9R/t97qtuf/cJ1ih7xH1TxHggRCDfNycH9KZDG8
    YljeOWLAEhV0U+fbnPEaNTJ2w2uwwYfNqhfJv8MlciMGVIYNU47TmA7Fk7dxZJ/+
    JzemjSLRXf9Xu85m7WM2qE7stixOmbSzl0bfErOQLmCMngECQQD4wL1iojSQhhCF
    yIgcg4xzXfx+FkeO/PGzJRsGYKyuLPomgQ5DBhxjeywNIZuWkbK8t2y26VNVzJzA
    qrL6Ch0pAkEAuY9kOi8p97ygVelb/3SEjAlQl4JJ/VB4tam3UTGzRwQCNUAq2iva
    P05ybe1IgJx7YT9CdYHdtcDqguNAFrUWIQJAP9qCAuquYZb4cM8cGW2vRQIQSXGA
    pvTJOnpA6K8yRHepMu8X8R6FdQfuM+S3orv9zLGtB3r3eGPQrShkTwj/mQJAUlkM
    RbYAjeyryvSQ20E+QVcw6MvtQfmgWB5FOEcyJGXnBPLBEak8ZbPOnHIdJtZK+tE0
    ESnc1ngSmpt3KZybgQJBAMqRN2WJ3L/Buz6Hylodnyd0J+Z9/dWvXVpWV5wQG5BS
    a18BEhX2iY7Udt08nKtuifJRDMq4sq97jgkDsBmR+E4=
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: rails-react-boilerplate.docker-registry
  namespace: concourse-main
type: Opaque
stringData:
  uri: registry.swarm.pw:443/rails-react-boilerplate
  pull-secret: registry-dockercfg
  username: registry-admin
  password: 67x9J4rMABBxa
---
apiVersion: v1
kind: Secret
metadata:
  name: rails-react-boilerplate.chart-repo
  namespace: concourse-main
type: Opaque
stringData:
  name: private
  uri: charts-admin:67x9J4rMABBxa@charts.swarm.pw
  chart: rails-app
