resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: generic-pipelines-repo
  type: git
  source:
    uri: https://github.com/ilyasotkov/concourse-pipelines.git
    branch: master

- name: pipelines-manifest-repo
  type: git
  source:
    uri: ((main.pipelines-repo-uri))
    branch: master

- name: pipelines-config
  type: concourse-pipeline
  source:
    target: ((main.target))
    insecure: "false"
    teams:
    - name: main
      username: ((main.username))
      password: ((main.password))

jobs:
- name: set-apps-pipelines
  plan:
  - get: generic-pipelines-repo
  - get: pipelines-manifest-repo
    trigger: true
  - put: pipelines-config
    params:
      pipelines_file: ((main.pipelines-file-path))
