groups:
- name: pull-request
  jobs:
  - test-pr

- name: master
  jobs:
  - test-master
  - integrate-master
  - version-master
  - tag-master
  - build-master
  - release-master

- name: production
  jobs:
  - merge-master-to-production
  - version-production
  - tag-production
  - build-production
  - release-production
  - start-next-rc

- name: bump-version
  jobs:
  - patch
  - minor
  - major
  - rc

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: helm
  type: docker-image
  source:
    repository: ilyasotkov/concourse-helm-resource

resources:
- name: pull-request
  type: pull-request
  source:
    repo: ((git_repo.name))
    access_token: ((git_repo.access_token))
    private_key: ((git_repo.private_key))
    every: true

- name: concource-pipelines-repo
  type: git
  source:
    uri: https://github.com/ilyasotkov/concourse-pipelines.git
    branch: master

- name: repo-master
  type: git
  source:
    uri: ((git_repo.uri))
    private_key: ((git_repo.private_key))
    branch: master

- name: repo-production
  type: git
  source:
    uri: ((git_repo.uri))
    private_key: ((git_repo.private_key))
    branch: production

- name: rc-version
  type: semver
  source:
    driver: git
    uri: ((git_repo.uri))
    private_key: ((git_repo.private_key))
    branch: rc-version
    file: version

- name: final-version
  type: semver
  source:
    driver: git
    uri: ((git_repo.uri))
    private_key: ((git_repo.private_key))
    branch: final-version
    file: version

- name: docker-image
  type: docker-image
  source:
    repository: ((docker_registry.uri))
    username: ((docker_registry.username))
    password: ((docker_registry.password))

- name: helm-release
  type: helm
  source:
    cluster_config: ((kube_config))
    repos:
    - name: private
      url: https://((chart_repo.username)):((chart_repo.password))@((chart_repo.uri))

jobs:
# ------------------------------------------------------------------------------
# Master branch jobs (released to staging)
# ------------------------------------------------------------------------------
- name: test-pr
  plan:
  - get: pull-request
    version: every
    trigger: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: test-pull-request
    file: pull-request/ci/tasks/unit.yml
    input_mapping:
      repo: pull-request
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure

- name: test-master
  plan:
  - get: repo-master
    trigger: true
  - task: unit
    file: repo-master/ci/tasks/unit.yml
    input_mapping: { repo: repo-master }

- name: integrate-master
  serial: true
  plan:
  - aggregate:
    - get: repo-master
      trigger: true
      passed: [ test-master ]
  - task: integration-test
    file: repo-master/ci/tasks/integration.yml
    input_mapping: { repo: repo-master }

- name: version-master
  serial: true
  serial_groups: [ update-version ]
  plan:
  - aggregate:
    - get: repo-master
      passed: [ integrate-master ]
      trigger: true
    - get: rc-version
  - put: rc-version
    params:
      pre: rc

- name: tag-master
  serial: true
  plan:
  - aggregate:
    - get: repo-master
      passed: [ version-master ]
      trigger: true
    - get: rc-version
      passed: [ version-master ]
  - put: repo-master
    params:
      repository: repo-master
      tag: rc-version/version

- name: build-master
  serial: true
  plan:
  - aggregate:
    - get: repo-master
      passed: [ version-master ]
      trigger: true
    - get: rc-version
      passed: [ version-master ]
  - put: docker-image
    params:
      build: repo-master
      tag: rc-version/version
      tag_as_latest: true
      # uncomment these two lines after initial image build and push
      # cache: true
      # cache_tag: latest

- name: release-master
  serial: true
  plan:
  - aggregate:
    - get: concource-pipelines-repo
    - get: repo-master
      passed: [ build-master ]
      trigger: true
    - get: rc-version
  - put: helm-release
    params:
      chart: private/((chart_repo.chart))
      release: repo-master/((master_release.name))
      values: repo-master/((master_release.values))
      replace: true
      devel: true
      recreate_pods: false
      wait_until_ready: 500
      override_values:
      - key: image.repository
        value: ((docker_registry.uri))
      - key: image.pullSecret
        value: registry-dockercfg
      - key: image.tag
        path: rc-version/version

# ------------------------------------------------------------------------------
# Production branch jobs (released to production)
# ------------------------------------------------------------------------------
- name: merge-master-to-production
  serial: true
  plan:
  - aggregate:
    - get: concource-pipelines-repo
    - get: repo-master
      # trigger: true
      # passed: [ release-master ]
    - get: repo-production
  - task: merge-master-to-production
    file: concource-pipelines-repo/tasks/merge-branch.yml
    input_mapping:
      pipelines: concource-pipelines-repo
      from: repo-master
      to: repo-production
    output_mapping:
      out: next-production
    params:
      GIT_EMAIL: concourse@ci.swarm.pw
      GIT_NAME: concourse
      NO_FF: true
  - put: repo-production
    params:
      repository: next-production

- name: version-production
  serial: true
  plan:
    - aggregate:
      - get: repo-production
        trigger: true
        passed: [ merge-master-to-production ]
      - get: rc-version
        params:
          bump: final
    - put: final-version
      params:
        file: rc-version/version

- name: tag-production
  serial: true
  plan:
  - aggregate:
    - get: repo-production
      passed: [ version-production ]
      trigger: true
    - get: final-version
      passed: [ version-production ]
  - put: repo-production
    params:
      repository: repo-production
      tag: final-version/version

- name: build-production
  serial: true
  plan:
  - aggregate:
    - get: repo-production
      passed: [ version-production ]
      trigger: true
    - get: rc-version
    - get: final-version
  - put: docker-image
    params:
      build: repo-production
      tag: final-version/version
      cache: true
      cache_tag: latest

- name: release-production
  serial: true
  plan:
  - aggregate:
    - get: repo-production
      passed: [ build-production ]
      trigger: true
    - get: final-version
  - put: helm-release
    params:
      chart: private/((chart_repo.chart))
      release: repo-production/((production_release.name))
      values: repo-production/((production_release.values))
      replace: true
      devel: true
      recreate_pods: false
      wait_until_ready: 500
      override_values:
      - key: image.pullSecret
        value: registry-dockercfg
      - key: image.tag
        path: final-version/version
      - key: image.repository
        value: ((docker_registry.uri))

- name: start-next-rc
  serial: true
  serial_groups: [ update-version ]
  plan:
    - get: final-version
      passed: [ tag-production ]
      trigger: true
      params:
        bump: patch
    # This initializes rc-verison with version
    # of the form 'x.y.z' temporalily.
    # However, we can gurantee that tagged versions on master branch
    # will be of the form 'x.y.z-rc.n' because version-master always
    # bump with {pre: rc}.
    - put: rc-version
      params:
        file: final-version/version

# ------------------------------------------------------------------------------
# SemVer version bumps. Must be triggered manually!
# ------------------------------------------------------------------------------
- name: patch
  serial: true
  serial_groups: [ update-version ]
  plan:
    - get: rc-version
    - put: rc-version
      params: { bump: patch }
      passed:
- name: minor
  serial: true
  serial_groups: [ update-version ]
  plan:
    - get: rc-version
    - put: rc-version
      params: { bump: minor }

- name: major
  serial: true
  serial_groups: [ update-version ]
  plan:
    - get: rc-version
    - put: rc-version
      params: { bump: major }

- name: rc
  serial: true
  serial_groups: [ update-version ]
  plan:
    - get: rc-version
    - put: rc-version
      params: { pre: rc }
